### ISSUE TITLE
suspected bug in modis_window

### ISSUE THREAD

**Issue by s-boeck** [WFP-VAM/modape#85]
Hi,

There seems to be something wrong with modis_window, I obtain (slightly) different results for the same data set depending on the -roi flag being set or not. Looks like some sort of projection issue, there are (presumably) regularly spaced horizontal bands of shifted pixels and some 'weird warped mesh' shift pattern on top (see screenshot; 'difference' image is scaled to emphasize the issue, real differences are obviously quite small). Tried to figure out which one's 'more correct', but didn't succeed...

![modis_wind_bug](https://user-images.githubusercontent.com/20515721/81838984-34d7dc80-9547-11ea-9d20-948b7f19d256.png)

**Comment by valpesendorfer** [comment]
Thanks for the issue.

Not surprised you didn't succeed figuring out which one's "more correct", as the answer is probably _neither_.  The warp will always yield different results depending on the raster dimension being warped. In this case, the clip is executed before the warp, resulting in slight differences compared to the non-clipped counterpart.

In the upcoming V1 release (as implemented with #104 ), the clip will be performed after the warp, yielding more coherent results. 

Since this is not really a bug as such, and is addressed in the upcoming release, I'll go ahead and close the issue.
